<a href="https://colab.research.google.com/github/phigratio/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#np.array
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]


In [4]:
# 2D and 3D array
a=np.array([[1,2],[4,5]],dtype=float)
print(a)
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[1. 2.]
 [4. 5.]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
#np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [7]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [8]:
# np.ones and np.zeros and np.random
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.random.random((3,4))

array([[0.2810818 , 0.16316651, 0.6064217 , 0.47584559],
       [0.54366699, 0.69401049, 0.96196144, 0.71668663],
       [0.64962731, 0.83090604, 0.78096838, 0.03336521]])

In [13]:
# np.linspace
np.linspace(-100,100,10)

array([-100.        ,  -77.77777778,  -55.55555556,  -33.33333333,
        -11.11111111,   11.11111111,   33.33333333,   55.55555556,
         77.77777778,  100.        ])

In [15]:
#np.identity
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [24]:
# Array attributes
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

#ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

#shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

#size
print(a3.size)
print(a2.size)
print(a1.size)

1
2
3
(10,)
(3, 4)
(2, 2, 2)
8
12
10


In [25]:
# itemsize
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [26]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64
