<a href="https://colab.research.google.com/github/phigratio/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
#np.array
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [25]:
# 2D and 3D array
a=np.array([[1,2],[4,5]],dtype=float)
print(a)
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[1. 2.]
 [4. 5.]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [26]:
#np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [28]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [29]:
# np.ones and np.zeros and np.random
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.random.random((3,4))

array([[0.44392208, 0.07236849, 0.68621236, 0.94878611],
       [0.6486715 , 0.09752674, 0.67209406, 0.03247999],
       [0.52867982, 0.16140954, 0.06460949, 0.24140428]])

In [32]:
# np.linspace
np.linspace(-100,100,10)

array([-100.        ,  -77.77777778,  -55.55555556,  -33.33333333,
        -11.11111111,   11.11111111,   33.33333333,   55.55555556,
         77.77777778,  100.        ])

In [33]:
#np.identity
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [34]:
# Array attributes
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

#ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

#shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

#size
print(a3.size)
print(a2.size)
print(a1.size)

1
2
3
(10,)
(3, 4)
(2, 2, 2)
8
12
10


In [35]:
# itemsize
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [36]:
#dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [37]:
# changing datatype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [39]:
# Array operations
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [40]:
#scalar operations
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [41]:
#arithmetic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [42]:
# relational
a2>15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [43]:
#vector operations
#arithmetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [44]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [45]:
#Functions
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[87., 12.,  8.],
       [19., 93., 97.],
       [69., 26., 20.]])

In [46]:
np.max(a1)

97.0

In [47]:
np.min(a1)

8.0

In [48]:
np.sum(a1)

431.0

In [49]:
np.prod(a1)

51363097194240.0

In [50]:
np.prod(a1,axis=0)

array([114057.,  29016.,  15520.])

In [52]:
#Statistical functions
np.mean(a1,axis=1)

array([35.66666667, 69.66666667, 38.33333333])

In [53]:
np.median(a1)

26.0

In [54]:
np.std(a1)

35.57915883224162

In [55]:
np.var(a1)

1265.8765432098767

In [56]:
#trigonometric functions
np.sin(a1)

array([[-0.82181784, -0.53657292,  0.98935825],
       [ 0.14987721, -0.94828214,  0.37960774],
       [-0.11478481,  0.76255845,  0.91294525]])

In [57]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [58]:
#log and exponents
np.log(a1)

array([[4.46590812, 2.48490665, 2.07944154],
       [2.94443898, 4.53259949, 4.57471098],
       [4.2341065 , 3.25809654, 2.99573227]])

In [59]:
np.exp(a1)

array([[6.07603023e+37, 1.62754791e+05, 2.98095799e+03],
       [1.78482301e+08, 2.45124554e+40, 1.33833472e+42],
       [9.25378173e+29, 1.95729609e+11, 4.85165195e+08]])

In [62]:
c=np.round(np.random.random((2,3))*100)
print(c)

[[11. 33. 96.]
 [50.  7. 11.]]


In [64]:
# Indexing and Slicing
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

print(a1[-1])

9
